// Catálogo de ejercicios — GymLog
// id estable, n = nombre, m = grupo muscular
const EXERCISES = [
  // Pecho
  {id:'press-banca', n:'Press banca', m:'Pecho'},
  {id:'press-banca-inclinado', n:'Press banca inclinado', m:'Pecho'},
  {id:'press-banca-declinado', n:'Press banca declinado', m:'Pecho'},
  {id:'press-mancuernas', n:'Press con mancuernas', m:'Pecho'},
  {id:'press-inclinado-mancuernas', n:'Press inclinado con mancuernas', m:'Pecho'},
  {id:'press-maquina', n:'Press en máquina', m:'Pecho'},
  {id:'aperturas-mancuernas', n:'Aperturas con mancuernas', m:'Pecho'},
  {id:'aperturas-polea', n:'Aperturas en polea (crossover)', m:'Pecho'},
  {id:'pec-deck', n:'Pec deck', m:'Pecho'},
  {id:'flexiones', n:'Flexiones', m:'Pecho'},
  {id:'fondos-pecho', n:'Fondos en paralelas (pecho)', m:'Pecho'},
  // Espalda
  {id:'dominadas', n:'Dominadas', m:'Espalda'},
  {id:'dominadas-supinas', n:'Dominadas supinas (chin-up)', m:'Espalda'},
  {id:'jalon-pecho', n:'Jalón al pecho', m:'Espalda'},
  {id:'jalon-agarre-cerrado', n:'Jalón agarre cerrado', m:'Espalda'},
  {id:'remo-barra', n:'Remo con barra', m:'Espalda'},
  {id:'remo-mancuerna', n:'Remo con mancuerna', m:'Espalda'},
  {id:'remo-polea-baja', n:'Remo en polea baja', m:'Espalda'},
  {id:'remo-maquina', n:'Remo en máquina', m:'Espalda'},
  {id:'pullover-polea', n:'Pullover en polea', m:'Espalda'},
  {id:'peso-muerto', n:'Peso muerto', m:'Espalda'},
  {id:'rack-pull', n:'Rack pull', m:'Espalda'},
  {id:'hiperextensiones', n:'Hiperextensiones', m:'Espalda'},
  // Hombros
  {id:'press-militar', n:'Press militar con barra', m:'Hombros'},
  {id:'press-militar-mancuernas', n:'Press militar con mancuernas', m:'Hombros'},
  {id:'press-arnold', n:'Press Arnold', m:'Hombros'},
  {id:'vuelos-laterales', n:'Vuelos laterales', m:'Hombros'},
  {id:'vuelos-laterales-polea', n:'Vuelos laterales en polea', m:'Hombros'},
  {id:'vuelos-posteriores', n:'Vuelos posteriores (pájaros)', m:'Hombros'},
  {id:'face-pull', n:'Face pull', m:'Hombros'},
  {id:'remo-menton', n:'Remo al mentón', m:'Hombros'},
  {id:'encogimientos', n:'Encogimientos (trapecio)', m:'Hombros'},
  // Bíceps
  {id:'curl-barra', n:'Curl con barra', m:'Bíceps'},
  {id:'curl-barra-z', n:'Curl con barra Z', m:'Bíceps'},
  {id:'curl-mancuernas', n:'Curl con mancuernas', m:'Bíceps'},
  {id:'curl-alternado', n:'Curl alternado', m:'Bíceps'},
  {id:'curl-martillo', n:'Curl martillo', m:'Bíceps'},
  {id:'curl-inclinado', n:'Curl inclinado', m:'Bíceps'},
  {id:'curl-concentrado', n:'Curl concentrado', m:'Bíceps'},
  {id:'curl-polea', n:'Curl en polea', m:'Bíceps'},
  {id:'curl-predicador', n:'Curl predicador', m:'Bíceps'},
  // Tríceps
  {id:'press-frances', n:'Press francés', m:'Tríceps'},
  {id:'extension-polea-soga', n:'Extensión en polea (soga)', m:'Tríceps'},
  {id:'extension-polea-barra', n:'Extensión en polea (barra)', m:'Tríceps'},
  {id:'extension-sobre-cabeza', n:'Extensión sobre cabeza', m:'Tríceps'},
  {id:'fondos-banco', n:'Fondos en banco', m:'Tríceps'},
  {id:'fondos-triceps', n:'Fondos en paralelas (tríceps)', m:'Tríceps'},
  {id:'patada-triceps', n:'Patada de tríceps', m:'Tríceps'},
  {id:'press-cerrado', n:'Press banca agarre cerrado', m:'Tríceps'},
  // Piernas
  {id:'sentadilla', n:'Sentadilla', m:'Piernas'},
  {id:'sentadilla-frontal', n:'Sentadilla frontal', m:'Piernas'},
  {id:'sentadilla-bulgara', n:'Sentadilla búlgara', m:'Piernas'},
  {id:'prensa', n:'Prensa', m:'Piernas'},
  {id:'hack-squat', n:'Hack squat', m:'Piernas'},
  {id:'extensiones-cuadriceps', n:'Extensiones de cuádriceps', m:'Piernas'},
  {id:'curl-femoral-acostado', n:'Curl femoral acostado', m:'Piernas'},
  {id:'curl-femoral-sentado', n:'Curl femoral sentado', m:'Piernas'},
  {id:'peso-muerto-rumano', n:'Peso muerto rumano', m:'Piernas'},
  {id:'buenos-dias', n:'Buenos días', m:'Piernas'},
  {id:'estocadas', n:'Estocadas', m:'Piernas'},
  {id:'zancadas-caminando', n:'Zancadas caminando', m:'Piernas'},
  {id:'aductores', n:'Aductores en máquina', m:'Piernas'},
  {id:'abductores', n:'Abductores en máquina', m:'Piernas'},
  {id:'gemelos-pie', n:'Gemelos de pie', m:'Piernas'},
  {id:'gemelos-sentado', n:'Gemelos sentado', m:'Piernas'},
  {id:'step-up', n:'Step up', m:'Piernas'},
  // Glúteos
  {id:'hip-thrust', n:'Hip thrust', m:'Glúteos'},
  {id:'puente-gluteos', n:'Puente de glúteos', m:'Glúteos'},
  {id:'patada-gluteo-polea', n:'Patada de glúteo en polea', m:'Glúteos'},
  // Core
  {id:'crunch', n:'Crunch', m:'Core'},
  {id:'crunch-polea', n:'Crunch en polea', m:'Core'},
  {id:'elevacion-piernas', n:'Elevación de piernas', m:'Core'},
  {id:'elevacion-rodillas-colgado', n:'Elevación de rodillas colgado', m:'Core'},
  {id:'plancha', n:'Plancha', m:'Core'},
  {id:'plancha-lateral', n:'Plancha lateral', m:'Core'},
  {id:'rueda-abdominal', n:'Rueda abdominal', m:'Core'},
  {id:'russian-twist', n:'Russian twist', m:'Core'},
  // Cardio
  {id:'cinta', n:'Cinta', m:'Cardio'},
  {id:'bicicleta', n:'Bicicleta', m:'Cardio'},
  {id:'eliptico', n:'Elíptico', m:'Cardio'},
  {id:'remo-ergometro', n:'Remo (ergómetro)', m:'Cardio'},
  {id:'escalador', n:'Escalador', m:'Cardio'},
  {id:'soga', n:'Saltar la soga', m:'Cardio'},
  {id:'burpees', n:'Burpees', m:'Cardio'}
];
const MUSCLES = ['Pecho','Espalda','Hombros','Bíceps','Tríceps','Piernas','Glúteos','Core','Cardio','Otro'];
